### ISSUE TITLE
-v23.permissions.* flags and the roaming profile

### ISSUE THREAD

**Issue by razvanm** [vanadium/core#10]
The [roaming profile](https://github.com/vanadium/core/tree/master/x/ref/runtime/factories/roaming) is pulling in the `-v23.permissions.file` and `-v23.permissions.literal` because the `__debug` is relying on them. That's confusing because the app might not actually use those flags at all. I think it would be better if there would be a separate set of flags that are only used by the `__debug` service.

**Comment by cosnicolaou** [comment]
ok, I'll rework the factories now that I've made the 'library' factory that's configured by exported variables rather than directly by flags. My plan is to reimplement the other factories to use the library one and to consequently simplify them all.

**Comment by cosnicolaou** [comment]
I made these flags a part of the core runtime initialization as of #52 and also made them accessible via the context. This seemed like the cleanest overall solution.

**Comment by razvanm** [comment]
Does this mean the `-v23.permissions.file` and `-v23.permissions.literal` only show up in `foo -help` or `foo help` when they really used by the app foo?

**Comment by cosnicolaou** [comment]
I believe it means that they always show up, which seems totally reasonable
to me. Or at least as reasonable as --v23.tcp.address showing up for client
that don't run servers!

Cheers, Cos.

**Comment by razvanm** [comment]
The mental model I have for `-v23.tcp.address` is that it controls the default address for the Vanadium RPC system. The problem with `-v23.permissions.file` and `-v23.permissions.literal` is that they give the impression that using them a user could control who can talk to the server by using them. That's not the case though unless the server is created in a particular way.

Going back to the `__debug`, I think having dedicated flags like `-v23.debug.permissions.file` and `-v23.debug.permissions.literal` for it would avoid any confusion but introduces the downside that the permissions are not in config.

**Comment by cosnicolaou** [comment]
On Tue, Jan 8, 2019 at 10:33 AM Razvan Musaloiu-E. <notifications@github.com>
wrote:

> The mental model I have for -v23.tcp.address is that it controls the
> default address for the Vanadium RPC system. The problem with
> -v23.permissions.file and -v23.permissions.literal is that they give the
> impression that using them a user could control who can talk to the server
> by using them. That's not the case though unless the server is created in a
> particular way.
>

ah yes, that's a fair point. I can change this behaviour though since I've
now cleaned up how the flags are defined and propagated so that they are
used implicitly. This may be annoying for GRAIL but wouldn't be a problem
otherwise.


> Going back to the __debug, I think having dedicated flags like
> -v23.debug.permissions.file and -v23.debug.permissions.literal for it
> would avoid any confusion but introduces the downside that the permissions
> are not in config.
>

what do you mean by 'not in config'?

Cheers, Cos.

**Comment by razvanm** [comment]
I managed to miss an important word. The

> [...] introduces the downside that the permissions are not in config.

should read:

> [...] introduces the downside that the permissions are not in **single** config.

**Comment by cosnicolaou** [comment]
ok, so how about I change the default WithNewServer to not accept an
explicit authorizer and instead create one from the context. I can then
provide another mechanism for specifying a custom authorizer, e.g. via a
different factory, that can either remove the flags or complain that they
are not going to do anything? If you agree in principle I'll scope
something out and run it by the GRAIL folks too.

Cheers, Cos.
