### ISSUE TITLE
Windows-compatibility in runtime/factories

### ISSUE THREAD

**Issue by byang223** [vanadium/core#103]
https://github.com/vanadium/core/blob/4b357db2fa619ffd546ea1a603cbd40bab8dd145/x/ref/runtime/factories/library/library.go#L5

Is it possible to include windows? I'm not too familiar with the implementations but is there a dependency that's not compatible with windows?

**Comment by cosnicolaou** [comment]
a factory could certainly be written for windows, but the current ones do have linux dependencies in terms of how they determine their local IP addresses etc.
