### ISSUE TITLE
go get v.io@v0.1.7 fails

### ISSUE THREAD

**Issue by yasushi-saito** [vanadium/core#110]
```
$ go version 
go version go1.14.1 linux/amd64
$ go get v.io@v0.1.7
go get: v.io@v0.1.7: parsing go.mod: go.mod:3: usage: go 1.23
```

I'm not sure  what this is.

**Comment by razvanm** [comment]
Tagging the current master with v0.1.8 should fix this issue. 

@cosnicolaou: any reasons not to do that?

**Comment by cosnicolaou** [comment]
This is because go 1.14 started enforcing that a go.mod file can't use major.minor versions for go. I was planning on bumping the tag after getting lint etc to work. You can work around it today by using @<githash>.

**Comment by razvanm** [comment]
This is fixed now, right?

**Comment by cosnicolaou** [comment]
yes.
