### ISSUE TITLE
remove v23agentd, and use ssh-agent instead

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/core#130]
v23agentd, or just agentd, was originally conceived to provide a secure enclave for private keys along the same lines as openssh's ssh-agent. However, in practice it has proved awkward to work with partly because of the need to ensure its prior installation but also due to the complexity of its implementation. That complexity arose from its use for multiple purposes and scenarios (e.g. for shared access to principal's blessings and roots, for launching processes in conjunction with the device manager, notification of blessing changes etc). One of the goals was to avoid publishing an easily discovered unprotected union domain socket but that required a parent/child process relationship between the agent and its clients (so as to use an anonymous socket) which was not possible in all situations without modifying an existing shell. The device manager, which is no longer used, was the only entity to take advantage of this and consequently agentd was forced to use a unix domain socket in the same way as ssh-agent. Agentd is therefore also vulnerable to being misused by root, but ssh-agent accepts this tradeof it seemed reasonable for agentd to do so also.

At the time of agentd's development (2013), the ssh-agent protocol was not formerly defined and we decided against using ssh-agent directly. However, as of 2016 it the ssh-agent [protocol](https://tools.ietf.org/html/draft-miller-ssh-agent-00) has been defined and Go language implementations of both the client and server side exist.  Using ssh-agent and SSH keys for signing will allow an easier integration with services that already use SSH keys (i.e., pretty much everything).

I plan to change the vanadium core code base as outlined below.

`x/ref/lib/security` provides support for managing in-memory and persistent credentials with the `x/ref/cmd/principal` being the primary means of manipulating principals and blessings. The runtime, via the agent, uses this package to load credentials. The following changes are planned:

1. split the current persistent principal into two types:
  - one that is generally used by the principal command to create/mutate a principal and its associated signed blessing and blessings roots.
  - one that is 'readonly' and periodically reloads its configuration from the file system. This will be used by the runtime in place of the agent. The reloading is important since it will allow a long service to see changes to its blessings without being restarted. This can both periodic and in response to a signal (SIGHUP).
2. introduce the notion of a signing service, which is simply a means of obtaining a security.Signer by some means or other. One means is from private key file (i.e., the current setup), the other is using ssh-agent as the signing service (I have prototyped this and it seems to work well). Another option is to use a hardware key store via the fido2 APIs. This is the most secure since each signing operation would require a key press or biometric validation.
3. currently the vanadium security package does not write out the public key directly but instead relies on it being obtained from the possibly password protected private key file. I plan to change the code to write out the public key file separately and to load it if the private key file is inaccessible. The motivation is that a principal with a public key file can not create sign `new` blessings but can validate existing ones.

**Comment by razvanm** [comment]
👍

**Comment by cosnicolaou** [comment]
Closed by #137.
