### ISSUE TITLE
Is Vanadium making a comeback?

### ISSUE THREAD

**Issue by asim** [vanadium/core#166]
Vanadium was a pretty interesting project a few years ago. I know the project stalled and most of the team left Google. Is this being picked up again? Who are the maintainers this time around? Whats the future goals of the project? Interested to learn more.

**Comment by cosnicolaou** [comment]
sorry, I assumed this was from someone else who worked on the project and I ignored it. I am still actively developing Vanadium and it's used by grail.com extensively. The near term plans are to continue to improve the core functionality of secure, authenticated RPC and service discovery. I do not plan on resurrecting the mobile device support in the near term.
