### ISSUE TITLE
v.io/x/ref/examples/fortune/fortune: what argument to pass to the -name flag?

### ISSUE THREAD

**Issue by joeblew99** [vanadium/core#3]
start server (v.io/x/ref/examples/fortune/fortuned):

````
./fortuned 
2016/08/10 02:33:44 Listening at: @6@wsh@192.168.1.119:56227@@c45e45f5bb455768e6b1044968976f9f@s@anonymous-banana-24465@x-MacBook-Pro.local@@

````

then client (v.io/x/ref/examples/fortune/fortune), seems to need a "name" as a flag.
Based on the Servers advertised address what is the name ?
I keep getting "no usable servers found" :)

**Comment by razvanm** [comment]
The argument for `-name` should be the string printed by the fortuned with a `/` in front. So, in the above example I expect the following to work:

```
./fortune --name =/@6@wsh@192.168.1.119:56227@@c45e45f5bb455768e6b1044968976f9f@s@anonymous-banana-24465@x-MacBook-Pro.local@@
```
