### ISSUE TITLE
Rare crash in rpc server-side code

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/core#49]
This crash has been observed both at GRAIL and on [travis](https://travis-ci.org/vanadium/core/builds/427871762) but only very rarely.

It appears due to race between accepting/authenticating a new connection and initializing the health checks for that connection. Both NewDialed and NewAccepted use a background [goroutine](https://github.com/vanadium/core/blob/5f384f3fba0b6f78ab711aae115656d9ea44e73a/x/ref/runtime/internal/flow/conn/conn.go#L332) to establish the connection but initialize the health checks in the [foreground](https://github.com/vanadium/core/blob/master/x/ref/runtime/internal/flow/conn/conn.go#L290). That background goroutine indirectly calls handleMessage, which is intended to process the expected handshake messages, however, handleMessage is also prepared to accept and act on an OpenFlow message. This means that the new flow may created via this call to handleMessage from the background goroutine or via the call to readLoop in the foreground one.  The crash can happen when an 'openflow' message is received before the health checks are initialized since the processing of that message attempts to update the healthcheck timeouts when that new flow is [created](https://github.com/vanadium/core/blob/5f384f3fba0b6f78ab711aae115656d9ea44e73a/x/ref/runtime/internal/flow/conn/conn.go#L870).

**Comment by razvanm** [comment]
Is there anything left to be done here?

**Comment by cosnicolaou** [comment]
I don’t think so.

Cheers, Cos.
