### ISSUE TITLE
Compression for Vanadium RPC payloads?

### ISSUE THREAD

**Issue by siddharthab** [vanadium/core#92]
This issue is actually a question.

Do the Vanadium RPCs have compression for their payloads? I am implementing a file sync service in Vanadium and the streaming payload will be blobs, each as a single `[]byte`. Just checking if I should be doing my own compression here.

Thanks.

**Comment by cosnicolaou** [comment]
I'm not sure we ever spoke about this in person, but there is no underlying compression applied. So yes, you should compress at the application level, but you probably already know that!

**Comment by siddharthab** [comment]
Thanks! I did end up compressing. 😄
